version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rmasci13
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  subscription-tracker:
    build: .
    container_name: subscription-tracker
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: rmasci13
      DB_PASSWORD: password
    networks:
      - db
    restart: unless-stopped
    ports:
      - "8080:8080"

networks:
  db:
    driver: bridge

volumes:
  db:
